services:
  soundgo_env:
    profiles: [dev]
    container_name: soundgo_env
    tty: true
    stdin_open: true
    image: soundgo:0.0.1
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - ~/.cache:/root/.cache/go-build
      - ~/go/pkg/mod:/go/pkg/mod
    ports:
      - 8080:8080
