services:
  # TEST DEVELOPMENT
  soundgo_env:
    profiles: [dev]
    container_name: soundgo_env
    tty: true
    stdin_open: true
    image: soundgo:0.0.1
    links:
      - db
    depends_on:
      - db
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - ~/.cache:/root/.cache/go-build
      - ~/go/pkg/mod:/go/pkg/mod
    environment:
      DB_USER: user
      DB_PORT: 5432
      DB_PASSWORD: password
      DB_NAME: soundgo
      DB_HOST: db
      GOOSE_DRIVER: postgres 
      GOOSE_DBSTRING: user=user password=password dbname=soundgo port=5432 host=db
      JWT_KEY: 6wrKJjEOcCPLw2tG7KqyzZ6IahTO9Oj2BX/mpZOY/ZAYEpPEkH8n3GA4WNTnOvwdwz680MC/r5G5quvhXey9Ww==
      PORT: 8000
    ports:
      - 8000:8000
      - 8080:8080
  db:
    profiles: [dev]
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: soundgo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d soundgo_test"]
      interval: 5s
      timeout: 60s

  # TEST ENVIRONMENT
  soundgo_test:
    profiles: [test]
    container_name: soundgo_test
    tty: true
    stdin_open: true
    image: soundgo:0.0.1
    links:
      - test_db
    depends_on:
      - test_db
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - ~/.cache:/root/.cache/go-build
      - ~/go/pkg/mod:/go/pkg/mod
    environment:
      DB_USER: user
      DB_PORT: 5432
      DB_PASSWORD: password
      DB_NAME: soundgo_test
      DB_HOST: test_db
      GOOSE_DRIVER: postgres 
      GOOSE_DBSTRING: user=user dbname=soundgo_test password=password port=5432 host=test_db
      JWT_KEY: 6wrKJjEOcCPLw2tG7KqyzZ6IahTO9Oj2BX/mpZOY/ZAYEpPEkH8n3GA4WNTnOvwdwz680MC/r5G5quvhXey9Ww==
      PORT: 8001
    ports:
      - 8001:8001
  test_db:
    profiles: [test]
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: soundgo_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d soundgo_test -U user"]
      interval: 1s
      timeout: 30s
      retries: 30
