// Code generated by ogen, DO NOT EDIT.
package api

type CheckHealthRes interface {
	checkHealthRes()
}

type CreateAudioRes interface {
	createAudioRes()
}

type CreatePasswordResetRequestRes interface {
	createPasswordResetRequestRes()
}

type CreateSessionRes interface {
	createSessionRes()
}

type CreateUserRes interface {
	createUserRes()
}

type DeleteSessionRes interface {
	deleteSessionRes()
}

type GetAudioFileRes interface {
	getAudioFileRes()
}

type GetAudioRes interface {
	getAudioRes()
}

type ResetPasswordRes interface {
	resetPasswordRes()
}

type UpdateUserRes interface {
	updateUserRes()
}
