// Code generated by ogen, DO NOT EDIT.
package api

type CreatePasswordResetRes interface {
	createPasswordResetRes()
}

type CreateSessionRes interface {
	createSessionRes()
}

type CreateUserRes interface {
	createUserRes()
}

type DeleteSessionRes interface {
	deleteSessionRes()
}

type ResetPasswordRes interface {
	resetPasswordRes()
}

type UpdateUserRes interface {
	updateUserRes()
}
