server:
  http_listen_port: 9080
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push
scrape_configs:
  - job_name: app
    pipeline_stages: 
      - json:
          expressions:
            output: msg
            timestamp: time
            level: level
            operation: operation
            duration: duration
            status_code: status_code
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - output:
          source: output
      - labels:
          level:
          operation:
          status_code:
    static_configs:
      - targets:
          - localhost
        labels:
          job: applogs
          __path__: /var/log/*log
